name: 🚀 Demande de nouveau projet
description: Créer un nouveau projet avec baseline automatisée
title: "[PROJET] "
labels: ["nouveau-projet", "à-valider"]
assignees:
  - younesbami

body:
  - type: markdown
    attributes:
      value: |
        ## Demande de création de projet
        
        Remplissez les informations ci-dessous pour créer automatiquement:
        - Namespace Kubernetes
        - Application ArgoCD 
        - Baseline avec ResourceQuota et RBAC
        
  - type: input
    id: project_name
    attributes:
      label: Nom du projet
      description: Nom court du projet (ex. ecommerce, api-users)
      placeholder: mon-super-projet
    validations:
      required: true
      
  - type: input
    id: team_name
    attributes:
      label: Équipe propriétaire
      description: Nom de l'équipe responsable du projet
      placeholder: platform
    validations:
      required: true
      
  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      description: Environnement de déploiement initial
      options:
        - dev
        - recette
        - preprod
        - prod
      default: 0
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description du projet
      description: Brève description du projet (optionnel)
      placeholder: Application web pour...
    validations:
      required: false
      
  - type: checkboxes
    id: confirmation
    attributes:
      label: Validation
      description: Confirmez que vous avez l'autorisation de créer ce projet
      options:
        - label: J'ai l'autorisation de créer ce projet pour mon équipe
          required: true