apiVersion: v1
kind: LimitRange
metadata:
  name: baseline-limits
  labels:
    platform.example.com/baseline-type: "large"
    platform.example.com/managed-by: "project-as-code"
spec:
  limits:
    - default:
        cpu: "1"
        memory: "1Gi"
      defaultRequest:
        cpu: "500m"
        memory: "512Mi"
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      type: Container