apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline-quota
  namespace: ecommerce-dev
  labels:
    platform.example.com/project: "ecommerce"
    platform.example.com/environment: "dev"
    platform.example.com/team: "backend-team"
    platform.example.com/managed-by: "project-as-code"
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    requests.storage: "10Gi"
    persistentvolumeclaims: "5"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "20"
