apiVersion: v1
kind: LimitRange
metadata:
  name: baseline-limits
  labels:
    platform.example.com/baseline-type: "standard"
    platform.example.com/managed-by: "project-as-code"
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
      type: Container