apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline-quota
  labels:
    platform.example.com/baseline-type: "standard"
    platform.example.com/managed-by: "project-as-code"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    requests.storage: "20Gi"
    persistentvolumeclaims: "5"
    pods: "30"
    services: "15"
    secrets: "15"
    configmaps: "30"