apiVersion: v1
kind: LimitRange
metadata:
  name: baseline-limits
  labels:
    platform.example.com/baseline-type: "restricted"
    platform.example.com/managed-by: "project-as-code"
spec:
  limits:
    - default:
        cpu: "100m"
        memory: "128Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "25m"
        memory: "32Mi"
      type: Container
